api:
  name: 'API: @project.name@'
  description: '@project.description@'
  version: '@project.version@'
server:
  port: 8081
  servlet:
    context-path: /nft-engine
spring:
  application:
    name: nft-engine
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
logging:
  level:
    org.mongodb.driver.cluster: off
    co.infoprice: debug
